# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
	source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_source = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
  let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
  let g:deoplete#sources#clang#sort_algo = 'priority'
  " let g:deoplete#sources#clang#clang_complete_database="./build/"
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre' # when a character is typed in Insert mode, before inserting the character
on_ft = 'snippet'
hook_source = '''
	source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
